#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WANeo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DbNeo")]
	public partial class DCNeoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblAccount(tblAccount instance);
    partial void UpdatetblAccount(tblAccount instance);
    partial void DeletetblAccount(tblAccount instance);
    partial void InsertTB_Neo(TB_Neo instance);
    partial void UpdateTB_Neo(TB_Neo instance);
    partial void DeleteTB_Neo(TB_Neo instance);
    #endregion
		
		public DCNeoDataContext() : 
				base(global::WANeo.Properties.Settings.Default.DbNeoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DCNeoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCNeoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCNeoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCNeoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblAccount> tblAccounts
		{
			get
			{
				return this.GetTable<tblAccount>();
			}
		}
		
		public System.Data.Linq.Table<TB_Neo> TB_Neos
		{
			get
			{
				return this.GetTable<TB_Neo>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_delete_tbl_Neo")]
		public int sp_delete_tbl_Neo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_update_tbl_Neo")]
		public int sp_update_tbl_Neo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Number", DbType="Int")] System.Nullable<int> number, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Peyvast", DbType="NVarChar(50)")] string peyvast, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ResultNeo", DbType="NVarChar(500)")] string resultNeo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comment", DbType="NVarChar(250)")] string comment)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, number, peyvast, resultNeo, comment);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertNeorecordAccount")]
		public int InsertNeorecordAccount([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Daramad", DbType="Int")] System.Nullable<int> daramad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Hazine", DbType="Int")] System.Nullable<int> hazine, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comment", DbType="NVarChar(200)")] string comment)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), daramad, hazine, comment);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertNeorecord")]
		public int InsertNeorecord(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> na, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> nb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> nc, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> nd, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ne, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> nf, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ng, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> nh, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ni, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> nj, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> nk, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> nl, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ea, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> eb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ec, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ed, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ee, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ef, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> eg, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> eh, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ei, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ej, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ek, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> el, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> oa, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ob, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> oc, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> od, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> oe, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> of, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> og, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> oh, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> oi, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> oj, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ok, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ol, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> aa, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ab, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ac, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ad, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ae, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> af, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ag, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ah, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ai, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> aj, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ak, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> al, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ca, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> cb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> cc, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> cd, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ce, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> cf, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> cg, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ch, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ci, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> cj, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ck, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> cl, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(50)")] string name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NameF", DbType="NVarChar(50)")] string nameF, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateNeo", DbType="NVarChar(10)")] string dateNeo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Meli", DbType="NVarChar(10)")] string meli, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Adress", DbType="NVarChar(100)")] string adress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhoneH", DbType="NVarChar(15)")] string phoneH, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhoneM", DbType="NVarChar(15)")] string phoneM, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumberSh", DbType="NVarChar(10)")] string numberSh, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LoEsh", DbType="NVarChar(100)")] string loEsh, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="N", DbType="Int")] System.Nullable<int> n, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="E", DbType="Int")] System.Nullable<int> e, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="O", DbType="Int")] System.Nullable<int> o, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="A", DbType="Int")] System.Nullable<int> a, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="C", DbType="Int")] System.Nullable<int> c, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> paj, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pad, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pba, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pbh, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pcd, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pch, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pdb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pdj, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pej, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> peh, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pfa, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pfb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pgj, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pgh, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pha, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> phb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pia, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pih, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pjb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pjh, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pka, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pkd, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pld, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> plh, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pmb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pmh, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pnj, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pnd, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ppb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> ppd, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> poa, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pod, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pqb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pqj, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pua, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> puj, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pwa, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pwj, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pxb, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> pxd, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pB, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pJ, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pH, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Number", DbType="Int")] System.Nullable<int> number, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Peyvast", DbType="NVarChar(50)")] string peyvast, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ResultNeo", DbType="NVarChar(500)")] string resultNeo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShoghlNext", DbType="NVarChar(100)")] string shoghlNext, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comment", DbType="NVarChar(250)")] string comment, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Price", DbType="Int")] System.Nullable<int> price)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), na, nb, nc, nd, ne, nf, ng, nh, ni, nj, nk, nl, ea, eb, ec, ed, ee, ef, eg, eh, ei, ej, ek, el, oa, ob, oc, od, oe, of, og, oh, oi, oj, ok, ol, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, ca, cb, cc, cd, ce, cf, cg, ch, ci, cj, ck, cl, name, nameF, dateNeo, meli, adress, phoneH, phoneM, numberSh, loEsh, n, e, o, a, c, paj, pad, pba, pbh, pcd, pch, pdb, pdj, pej, peh, pfa, pfb, pgj, pgh, pha, phb, pia, pih, pjb, pjh, pka, pkd, pld, plh, pmb, pmh, pnj, pnd, ppb, ppd, poa, pod, pqb, pqj, pua, puj, pwa, pwj, pxb, pxd, pA, pB, pJ, pD, pH, number, peyvast, resultNeo, shoghlNext, comment, price);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAccount")]
	public partial class tblAccount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AccountID;
		
		private System.Nullable<int> _Daramad;
		
		private System.Nullable<int> _Hazine;
		
		private string _Comment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAccountIDChanging(int value);
    partial void OnAccountIDChanged();
    partial void OnDaramadChanging(System.Nullable<int> value);
    partial void OnDaramadChanged();
    partial void OnHazineChanging(System.Nullable<int> value);
    partial void OnHazineChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    #endregion
		
		public tblAccount()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AccountID
		{
			get
			{
				return this._AccountID;
			}
			set
			{
				if ((this._AccountID != value))
				{
					this.OnAccountIDChanging(value);
					this.SendPropertyChanging();
					this._AccountID = value;
					this.SendPropertyChanged("AccountID");
					this.OnAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Daramad", DbType="Int")]
		public System.Nullable<int> Daramad
		{
			get
			{
				return this._Daramad;
			}
			set
			{
				if ((this._Daramad != value))
				{
					this.OnDaramadChanging(value);
					this.SendPropertyChanging();
					this._Daramad = value;
					this.SendPropertyChanged("Daramad");
					this.OnDaramadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hazine", DbType="Int")]
		public System.Nullable<int> Hazine
		{
			get
			{
				return this._Hazine;
			}
			set
			{
				if ((this._Hazine != value))
				{
					this.OnHazineChanging(value);
					this.SendPropertyChanging();
					this._Hazine = value;
					this.SendPropertyChanged("Hazine");
					this.OnHazineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(200)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Neo")]
	public partial class TB_Neo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<byte> _na;
		
		private System.Nullable<byte> _nb;
		
		private System.Nullable<byte> _nc;
		
		private System.Nullable<byte> _nd;
		
		private System.Nullable<byte> _ne;
		
		private System.Nullable<byte> _nf;
		
		private System.Nullable<byte> _ng;
		
		private System.Nullable<byte> _nh;
		
		private System.Nullable<byte> _ni;
		
		private System.Nullable<byte> _nj;
		
		private System.Nullable<byte> _nk;
		
		private System.Nullable<byte> _nl;
		
		private System.Nullable<byte> _ea;
		
		private System.Nullable<byte> _eb;
		
		private System.Nullable<byte> _ec;
		
		private System.Nullable<byte> _ed;
		
		private System.Nullable<byte> _ee;
		
		private System.Nullable<byte> _ef;
		
		private System.Nullable<byte> _eg;
		
		private System.Nullable<byte> _eh;
		
		private System.Nullable<byte> _ei;
		
		private System.Nullable<byte> _ej;
		
		private System.Nullable<byte> _ek;
		
		private System.Nullable<byte> _el;
		
		private System.Nullable<byte> _oa;
		
		private System.Nullable<byte> _ob;
		
		private System.Nullable<byte> _oc;
		
		private System.Nullable<byte> _od;
		
		private System.Nullable<byte> _oe;
		
		private System.Nullable<byte> _of;
		
		private System.Nullable<byte> _og;
		
		private System.Nullable<byte> _oh;
		
		private System.Nullable<byte> _oi;
		
		private System.Nullable<byte> _oj;
		
		private System.Nullable<byte> _ok;
		
		private System.Nullable<byte> _ol;
		
		private System.Nullable<byte> _aa;
		
		private System.Nullable<byte> _ab;
		
		private System.Nullable<byte> _ac;
		
		private System.Nullable<byte> _ad;
		
		private System.Nullable<byte> _ae;
		
		private System.Nullable<byte> _af;
		
		private System.Nullable<byte> _ag;
		
		private System.Nullable<byte> _ah;
		
		private System.Nullable<byte> _ai;
		
		private System.Nullable<byte> _aj;
		
		private System.Nullable<byte> _ak;
		
		private System.Nullable<byte> _al;
		
		private System.Nullable<byte> _ca;
		
		private System.Nullable<byte> _cb;
		
		private System.Nullable<byte> _cc;
		
		private System.Nullable<byte> _cd;
		
		private System.Nullable<byte> _ce;
		
		private System.Nullable<byte> _cf;
		
		private System.Nullable<byte> _cg;
		
		private System.Nullable<byte> _ch;
		
		private System.Nullable<byte> _ci;
		
		private System.Nullable<byte> _cj;
		
		private System.Nullable<byte> _ck;
		
		private System.Nullable<byte> _cl;
		
		private string _Name;
		
		private string _NameF;
		
		private string _DateNeo;
		
		private string _Meli;
		
		private string _Adress;
		
		private string _PhoneH;
		
		private string _PhoneM;
		
		private string _NumberSh;
		
		private string _LoEsh;
		
		private System.Nullable<int> _N;
		
		private System.Nullable<int> _E;
		
		private System.Nullable<int> _O;
		
		private System.Nullable<int> _A;
		
		private System.Nullable<int> _C;
		
		private System.Nullable<byte> _paj;
		
		private System.Nullable<byte> _pad;
		
		private System.Nullable<byte> _pba;
		
		private System.Nullable<byte> _pbh;
		
		private System.Nullable<byte> _pcd;
		
		private System.Nullable<byte> _pch;
		
		private System.Nullable<byte> _pdb;
		
		private System.Nullable<byte> _pdj;
		
		private System.Nullable<byte> _pej;
		
		private System.Nullable<byte> _peh;
		
		private System.Nullable<byte> _pfa;
		
		private System.Nullable<byte> _pfb;
		
		private System.Nullable<byte> _pgj;
		
		private System.Nullable<byte> _pgh;
		
		private System.Nullable<byte> _pha;
		
		private System.Nullable<byte> _phb;
		
		private System.Nullable<byte> _pia;
		
		private System.Nullable<byte> _pih;
		
		private System.Nullable<byte> _pjb;
		
		private System.Nullable<byte> _pjh;
		
		private System.Nullable<byte> _pka;
		
		private System.Nullable<byte> _pkd;
		
		private System.Nullable<byte> _pld;
		
		private System.Nullable<byte> _plh;
		
		private System.Nullable<byte> _pmb;
		
		private System.Nullable<byte> _pmh;
		
		private System.Nullable<byte> _pnj;
		
		private System.Nullable<byte> _pnd;
		
		private System.Nullable<byte> _ppb;
		
		private System.Nullable<byte> _ppd;
		
		private System.Nullable<byte> _poa;
		
		private System.Nullable<byte> _pod;
		
		private System.Nullable<byte> _pqb;
		
		private System.Nullable<byte> _pqj;
		
		private System.Nullable<byte> _pua;
		
		private System.Nullable<byte> _puj;
		
		private System.Nullable<byte> _pwa;
		
		private System.Nullable<byte> _pwj;
		
		private System.Nullable<byte> _pxb;
		
		private System.Nullable<byte> _pxd;
		
		private System.Nullable<int> _PA;
		
		private System.Nullable<int> _PB;
		
		private System.Nullable<int> _PJ;
		
		private System.Nullable<int> _PD;
		
		private System.Nullable<int> _PH;
		
		private System.Nullable<int> _Number;
		
		private string _Peyvast;
		
		private string _ResultNeo;
		
		private string _ShoghlNext;
		
		private string _Comment;
		
		private System.Nullable<int> _Price;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnaChanging(System.Nullable<byte> value);
    partial void OnnaChanged();
    partial void OnnbChanging(System.Nullable<byte> value);
    partial void OnnbChanged();
    partial void OnncChanging(System.Nullable<byte> value);
    partial void OnncChanged();
    partial void OnndChanging(System.Nullable<byte> value);
    partial void OnndChanged();
    partial void OnneChanging(System.Nullable<byte> value);
    partial void OnneChanged();
    partial void OnnfChanging(System.Nullable<byte> value);
    partial void OnnfChanged();
    partial void OnngChanging(System.Nullable<byte> value);
    partial void OnngChanged();
    partial void OnnhChanging(System.Nullable<byte> value);
    partial void OnnhChanged();
    partial void OnniChanging(System.Nullable<byte> value);
    partial void OnniChanged();
    partial void OnnjChanging(System.Nullable<byte> value);
    partial void OnnjChanged();
    partial void OnnkChanging(System.Nullable<byte> value);
    partial void OnnkChanged();
    partial void OnnlChanging(System.Nullable<byte> value);
    partial void OnnlChanged();
    partial void OneaChanging(System.Nullable<byte> value);
    partial void OneaChanged();
    partial void OnebChanging(System.Nullable<byte> value);
    partial void OnebChanged();
    partial void OnecChanging(System.Nullable<byte> value);
    partial void OnecChanged();
    partial void OnedChanging(System.Nullable<byte> value);
    partial void OnedChanged();
    partial void OneeChanging(System.Nullable<byte> value);
    partial void OneeChanged();
    partial void OnefChanging(System.Nullable<byte> value);
    partial void OnefChanged();
    partial void OnegChanging(System.Nullable<byte> value);
    partial void OnegChanged();
    partial void OnehChanging(System.Nullable<byte> value);
    partial void OnehChanged();
    partial void OneiChanging(System.Nullable<byte> value);
    partial void OneiChanged();
    partial void OnejChanging(System.Nullable<byte> value);
    partial void OnejChanged();
    partial void OnekChanging(System.Nullable<byte> value);
    partial void OnekChanged();
    partial void OnelChanging(System.Nullable<byte> value);
    partial void OnelChanged();
    partial void OnoaChanging(System.Nullable<byte> value);
    partial void OnoaChanged();
    partial void OnobChanging(System.Nullable<byte> value);
    partial void OnobChanged();
    partial void OnocChanging(System.Nullable<byte> value);
    partial void OnocChanged();
    partial void OnodChanging(System.Nullable<byte> value);
    partial void OnodChanged();
    partial void OnoeChanging(System.Nullable<byte> value);
    partial void OnoeChanged();
    partial void OnofChanging(System.Nullable<byte> value);
    partial void OnofChanged();
    partial void OnogChanging(System.Nullable<byte> value);
    partial void OnogChanged();
    partial void OnohChanging(System.Nullable<byte> value);
    partial void OnohChanged();
    partial void OnoiChanging(System.Nullable<byte> value);
    partial void OnoiChanged();
    partial void OnojChanging(System.Nullable<byte> value);
    partial void OnojChanged();
    partial void OnokChanging(System.Nullable<byte> value);
    partial void OnokChanged();
    partial void OnolChanging(System.Nullable<byte> value);
    partial void OnolChanged();
    partial void OnaaChanging(System.Nullable<byte> value);
    partial void OnaaChanged();
    partial void OnabChanging(System.Nullable<byte> value);
    partial void OnabChanged();
    partial void OnacChanging(System.Nullable<byte> value);
    partial void OnacChanged();
    partial void OnadChanging(System.Nullable<byte> value);
    partial void OnadChanged();
    partial void OnaeChanging(System.Nullable<byte> value);
    partial void OnaeChanged();
    partial void OnafChanging(System.Nullable<byte> value);
    partial void OnafChanged();
    partial void OnagChanging(System.Nullable<byte> value);
    partial void OnagChanged();
    partial void OnahChanging(System.Nullable<byte> value);
    partial void OnahChanged();
    partial void OnaiChanging(System.Nullable<byte> value);
    partial void OnaiChanged();
    partial void OnajChanging(System.Nullable<byte> value);
    partial void OnajChanged();
    partial void OnakChanging(System.Nullable<byte> value);
    partial void OnakChanged();
    partial void OnalChanging(System.Nullable<byte> value);
    partial void OnalChanged();
    partial void OncaChanging(System.Nullable<byte> value);
    partial void OncaChanged();
    partial void OncbChanging(System.Nullable<byte> value);
    partial void OncbChanged();
    partial void OnccChanging(System.Nullable<byte> value);
    partial void OnccChanged();
    partial void OncdChanging(System.Nullable<byte> value);
    partial void OncdChanged();
    partial void OnceChanging(System.Nullable<byte> value);
    partial void OnceChanged();
    partial void OncfChanging(System.Nullable<byte> value);
    partial void OncfChanged();
    partial void OncgChanging(System.Nullable<byte> value);
    partial void OncgChanged();
    partial void OnchChanging(System.Nullable<byte> value);
    partial void OnchChanged();
    partial void OnciChanging(System.Nullable<byte> value);
    partial void OnciChanged();
    partial void OncjChanging(System.Nullable<byte> value);
    partial void OncjChanged();
    partial void OnckChanging(System.Nullable<byte> value);
    partial void OnckChanged();
    partial void OnclChanging(System.Nullable<byte> value);
    partial void OnclChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnNameFChanging(string value);
    partial void OnNameFChanged();
    partial void OnDateNeoChanging(string value);
    partial void OnDateNeoChanged();
    partial void OnMeliChanging(string value);
    partial void OnMeliChanged();
    partial void OnAdressChanging(string value);
    partial void OnAdressChanged();
    partial void OnPhoneHChanging(string value);
    partial void OnPhoneHChanged();
    partial void OnPhoneMChanging(string value);
    partial void OnPhoneMChanged();
    partial void OnNumberShChanging(string value);
    partial void OnNumberShChanged();
    partial void OnLoEshChanging(string value);
    partial void OnLoEshChanged();
    partial void OnNChanging(System.Nullable<int> value);
    partial void OnNChanged();
    partial void OnEChanging(System.Nullable<int> value);
    partial void OnEChanged();
    partial void OnOChanging(System.Nullable<int> value);
    partial void OnOChanged();
    partial void OnAChanging(System.Nullable<int> value);
    partial void OnAChanged();
    partial void OnCChanging(System.Nullable<int> value);
    partial void OnCChanged();
    partial void OnpajChanging(System.Nullable<byte> value);
    partial void OnpajChanged();
    partial void OnpadChanging(System.Nullable<byte> value);
    partial void OnpadChanged();
    partial void OnpbaChanging(System.Nullable<byte> value);
    partial void OnpbaChanged();
    partial void OnpbhChanging(System.Nullable<byte> value);
    partial void OnpbhChanged();
    partial void OnpcdChanging(System.Nullable<byte> value);
    partial void OnpcdChanged();
    partial void OnpchChanging(System.Nullable<byte> value);
    partial void OnpchChanged();
    partial void OnpdbChanging(System.Nullable<byte> value);
    partial void OnpdbChanged();
    partial void OnpdjChanging(System.Nullable<byte> value);
    partial void OnpdjChanged();
    partial void OnpejChanging(System.Nullable<byte> value);
    partial void OnpejChanged();
    partial void OnpehChanging(System.Nullable<byte> value);
    partial void OnpehChanged();
    partial void OnpfaChanging(System.Nullable<byte> value);
    partial void OnpfaChanged();
    partial void OnpfbChanging(System.Nullable<byte> value);
    partial void OnpfbChanged();
    partial void OnpgjChanging(System.Nullable<byte> value);
    partial void OnpgjChanged();
    partial void OnpghChanging(System.Nullable<byte> value);
    partial void OnpghChanged();
    partial void OnphaChanging(System.Nullable<byte> value);
    partial void OnphaChanged();
    partial void OnphbChanging(System.Nullable<byte> value);
    partial void OnphbChanged();
    partial void OnpiaChanging(System.Nullable<byte> value);
    partial void OnpiaChanged();
    partial void OnpihChanging(System.Nullable<byte> value);
    partial void OnpihChanged();
    partial void OnpjbChanging(System.Nullable<byte> value);
    partial void OnpjbChanged();
    partial void OnpjhChanging(System.Nullable<byte> value);
    partial void OnpjhChanged();
    partial void OnpkaChanging(System.Nullable<byte> value);
    partial void OnpkaChanged();
    partial void OnpkdChanging(System.Nullable<byte> value);
    partial void OnpkdChanged();
    partial void OnpldChanging(System.Nullable<byte> value);
    partial void OnpldChanged();
    partial void OnplhChanging(System.Nullable<byte> value);
    partial void OnplhChanged();
    partial void OnpmbChanging(System.Nullable<byte> value);
    partial void OnpmbChanged();
    partial void OnpmhChanging(System.Nullable<byte> value);
    partial void OnpmhChanged();
    partial void OnpnjChanging(System.Nullable<byte> value);
    partial void OnpnjChanged();
    partial void OnpndChanging(System.Nullable<byte> value);
    partial void OnpndChanged();
    partial void OnppbChanging(System.Nullable<byte> value);
    partial void OnppbChanged();
    partial void OnppdChanging(System.Nullable<byte> value);
    partial void OnppdChanged();
    partial void OnpoaChanging(System.Nullable<byte> value);
    partial void OnpoaChanged();
    partial void OnpodChanging(System.Nullable<byte> value);
    partial void OnpodChanged();
    partial void OnpqbChanging(System.Nullable<byte> value);
    partial void OnpqbChanged();
    partial void OnpqjChanging(System.Nullable<byte> value);
    partial void OnpqjChanged();
    partial void OnpuaChanging(System.Nullable<byte> value);
    partial void OnpuaChanged();
    partial void OnpujChanging(System.Nullable<byte> value);
    partial void OnpujChanged();
    partial void OnpwaChanging(System.Nullable<byte> value);
    partial void OnpwaChanged();
    partial void OnpwjChanging(System.Nullable<byte> value);
    partial void OnpwjChanged();
    partial void OnpxbChanging(System.Nullable<byte> value);
    partial void OnpxbChanged();
    partial void OnpxdChanging(System.Nullable<byte> value);
    partial void OnpxdChanged();
    partial void OnPAChanging(System.Nullable<int> value);
    partial void OnPAChanged();
    partial void OnPBChanging(System.Nullable<int> value);
    partial void OnPBChanged();
    partial void OnPJChanging(System.Nullable<int> value);
    partial void OnPJChanged();
    partial void OnPDChanging(System.Nullable<int> value);
    partial void OnPDChanged();
    partial void OnPHChanging(System.Nullable<int> value);
    partial void OnPHChanged();
    partial void OnNumberChanging(System.Nullable<int> value);
    partial void OnNumberChanged();
    partial void OnPeyvastChanging(string value);
    partial void OnPeyvastChanged();
    partial void OnResultNeoChanging(string value);
    partial void OnResultNeoChanged();
    partial void OnShoghlNextChanging(string value);
    partial void OnShoghlNextChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnPriceChanging(System.Nullable<int> value);
    partial void OnPriceChanged();
    #endregion
		
		public TB_Neo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_na", DbType="TinyInt")]
		public System.Nullable<byte> na
		{
			get
			{
				return this._na;
			}
			set
			{
				if ((this._na != value))
				{
					this.OnnaChanging(value);
					this.SendPropertyChanging();
					this._na = value;
					this.SendPropertyChanged("na");
					this.OnnaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nb", DbType="TinyInt")]
		public System.Nullable<byte> nb
		{
			get
			{
				return this._nb;
			}
			set
			{
				if ((this._nb != value))
				{
					this.OnnbChanging(value);
					this.SendPropertyChanging();
					this._nb = value;
					this.SendPropertyChanged("nb");
					this.OnnbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nc", DbType="TinyInt")]
		public System.Nullable<byte> nc
		{
			get
			{
				return this._nc;
			}
			set
			{
				if ((this._nc != value))
				{
					this.OnncChanging(value);
					this.SendPropertyChanging();
					this._nc = value;
					this.SendPropertyChanged("nc");
					this.OnncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nd", DbType="TinyInt")]
		public System.Nullable<byte> nd
		{
			get
			{
				return this._nd;
			}
			set
			{
				if ((this._nd != value))
				{
					this.OnndChanging(value);
					this.SendPropertyChanging();
					this._nd = value;
					this.SendPropertyChanged("nd");
					this.OnndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ne", DbType="TinyInt")]
		public System.Nullable<byte> ne
		{
			get
			{
				return this._ne;
			}
			set
			{
				if ((this._ne != value))
				{
					this.OnneChanging(value);
					this.SendPropertyChanging();
					this._ne = value;
					this.SendPropertyChanged("ne");
					this.OnneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nf", DbType="TinyInt")]
		public System.Nullable<byte> nf
		{
			get
			{
				return this._nf;
			}
			set
			{
				if ((this._nf != value))
				{
					this.OnnfChanging(value);
					this.SendPropertyChanging();
					this._nf = value;
					this.SendPropertyChanged("nf");
					this.OnnfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ng", DbType="TinyInt")]
		public System.Nullable<byte> ng
		{
			get
			{
				return this._ng;
			}
			set
			{
				if ((this._ng != value))
				{
					this.OnngChanging(value);
					this.SendPropertyChanging();
					this._ng = value;
					this.SendPropertyChanged("ng");
					this.OnngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nh", DbType="TinyInt")]
		public System.Nullable<byte> nh
		{
			get
			{
				return this._nh;
			}
			set
			{
				if ((this._nh != value))
				{
					this.OnnhChanging(value);
					this.SendPropertyChanging();
					this._nh = value;
					this.SendPropertyChanged("nh");
					this.OnnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ni", DbType="TinyInt")]
		public System.Nullable<byte> ni
		{
			get
			{
				return this._ni;
			}
			set
			{
				if ((this._ni != value))
				{
					this.OnniChanging(value);
					this.SendPropertyChanging();
					this._ni = value;
					this.SendPropertyChanged("ni");
					this.OnniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nj", DbType="TinyInt")]
		public System.Nullable<byte> nj
		{
			get
			{
				return this._nj;
			}
			set
			{
				if ((this._nj != value))
				{
					this.OnnjChanging(value);
					this.SendPropertyChanging();
					this._nj = value;
					this.SendPropertyChanged("nj");
					this.OnnjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nk", DbType="TinyInt")]
		public System.Nullable<byte> nk
		{
			get
			{
				return this._nk;
			}
			set
			{
				if ((this._nk != value))
				{
					this.OnnkChanging(value);
					this.SendPropertyChanging();
					this._nk = value;
					this.SendPropertyChanged("nk");
					this.OnnkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nl", DbType="TinyInt")]
		public System.Nullable<byte> nl
		{
			get
			{
				return this._nl;
			}
			set
			{
				if ((this._nl != value))
				{
					this.OnnlChanging(value);
					this.SendPropertyChanging();
					this._nl = value;
					this.SendPropertyChanged("nl");
					this.OnnlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ea", DbType="TinyInt")]
		public System.Nullable<byte> ea
		{
			get
			{
				return this._ea;
			}
			set
			{
				if ((this._ea != value))
				{
					this.OneaChanging(value);
					this.SendPropertyChanging();
					this._ea = value;
					this.SendPropertyChanged("ea");
					this.OneaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eb", DbType="TinyInt")]
		public System.Nullable<byte> eb
		{
			get
			{
				return this._eb;
			}
			set
			{
				if ((this._eb != value))
				{
					this.OnebChanging(value);
					this.SendPropertyChanging();
					this._eb = value;
					this.SendPropertyChanged("eb");
					this.OnebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ec", DbType="TinyInt")]
		public System.Nullable<byte> ec
		{
			get
			{
				return this._ec;
			}
			set
			{
				if ((this._ec != value))
				{
					this.OnecChanging(value);
					this.SendPropertyChanging();
					this._ec = value;
					this.SendPropertyChanged("ec");
					this.OnecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ed", DbType="TinyInt")]
		public System.Nullable<byte> ed
		{
			get
			{
				return this._ed;
			}
			set
			{
				if ((this._ed != value))
				{
					this.OnedChanging(value);
					this.SendPropertyChanging();
					this._ed = value;
					this.SendPropertyChanged("ed");
					this.OnedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ee", DbType="TinyInt")]
		public System.Nullable<byte> ee
		{
			get
			{
				return this._ee;
			}
			set
			{
				if ((this._ee != value))
				{
					this.OneeChanging(value);
					this.SendPropertyChanging();
					this._ee = value;
					this.SendPropertyChanged("ee");
					this.OneeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ef", DbType="TinyInt")]
		public System.Nullable<byte> ef
		{
			get
			{
				return this._ef;
			}
			set
			{
				if ((this._ef != value))
				{
					this.OnefChanging(value);
					this.SendPropertyChanging();
					this._ef = value;
					this.SendPropertyChanged("ef");
					this.OnefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eg", DbType="TinyInt")]
		public System.Nullable<byte> eg
		{
			get
			{
				return this._eg;
			}
			set
			{
				if ((this._eg != value))
				{
					this.OnegChanging(value);
					this.SendPropertyChanging();
					this._eg = value;
					this.SendPropertyChanged("eg");
					this.OnegChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eh", DbType="TinyInt")]
		public System.Nullable<byte> eh
		{
			get
			{
				return this._eh;
			}
			set
			{
				if ((this._eh != value))
				{
					this.OnehChanging(value);
					this.SendPropertyChanging();
					this._eh = value;
					this.SendPropertyChanged("eh");
					this.OnehChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ei", DbType="TinyInt")]
		public System.Nullable<byte> ei
		{
			get
			{
				return this._ei;
			}
			set
			{
				if ((this._ei != value))
				{
					this.OneiChanging(value);
					this.SendPropertyChanging();
					this._ei = value;
					this.SendPropertyChanged("ei");
					this.OneiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ej", DbType="TinyInt")]
		public System.Nullable<byte> ej
		{
			get
			{
				return this._ej;
			}
			set
			{
				if ((this._ej != value))
				{
					this.OnejChanging(value);
					this.SendPropertyChanging();
					this._ej = value;
					this.SendPropertyChanged("ej");
					this.OnejChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ek", DbType="TinyInt")]
		public System.Nullable<byte> ek
		{
			get
			{
				return this._ek;
			}
			set
			{
				if ((this._ek != value))
				{
					this.OnekChanging(value);
					this.SendPropertyChanging();
					this._ek = value;
					this.SendPropertyChanged("ek");
					this.OnekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_el", DbType="TinyInt")]
		public System.Nullable<byte> el
		{
			get
			{
				return this._el;
			}
			set
			{
				if ((this._el != value))
				{
					this.OnelChanging(value);
					this.SendPropertyChanging();
					this._el = value;
					this.SendPropertyChanged("el");
					this.OnelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oa", DbType="TinyInt")]
		public System.Nullable<byte> oa
		{
			get
			{
				return this._oa;
			}
			set
			{
				if ((this._oa != value))
				{
					this.OnoaChanging(value);
					this.SendPropertyChanging();
					this._oa = value;
					this.SendPropertyChanged("oa");
					this.OnoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ob", DbType="TinyInt")]
		public System.Nullable<byte> ob
		{
			get
			{
				return this._ob;
			}
			set
			{
				if ((this._ob != value))
				{
					this.OnobChanging(value);
					this.SendPropertyChanging();
					this._ob = value;
					this.SendPropertyChanged("ob");
					this.OnobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oc", DbType="TinyInt")]
		public System.Nullable<byte> oc
		{
			get
			{
				return this._oc;
			}
			set
			{
				if ((this._oc != value))
				{
					this.OnocChanging(value);
					this.SendPropertyChanging();
					this._oc = value;
					this.SendPropertyChanged("oc");
					this.OnocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_od", DbType="TinyInt")]
		public System.Nullable<byte> od
		{
			get
			{
				return this._od;
			}
			set
			{
				if ((this._od != value))
				{
					this.OnodChanging(value);
					this.SendPropertyChanging();
					this._od = value;
					this.SendPropertyChanged("od");
					this.OnodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oe", DbType="TinyInt")]
		public System.Nullable<byte> oe
		{
			get
			{
				return this._oe;
			}
			set
			{
				if ((this._oe != value))
				{
					this.OnoeChanging(value);
					this.SendPropertyChanging();
					this._oe = value;
					this.SendPropertyChanged("oe");
					this.OnoeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[of]", Storage="_of", DbType="TinyInt")]
		public System.Nullable<byte> of
		{
			get
			{
				return this._of;
			}
			set
			{
				if ((this._of != value))
				{
					this.OnofChanging(value);
					this.SendPropertyChanging();
					this._of = value;
					this.SendPropertyChanged("of");
					this.OnofChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_og", DbType="TinyInt")]
		public System.Nullable<byte> og
		{
			get
			{
				return this._og;
			}
			set
			{
				if ((this._og != value))
				{
					this.OnogChanging(value);
					this.SendPropertyChanging();
					this._og = value;
					this.SendPropertyChanged("og");
					this.OnogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oh", DbType="TinyInt")]
		public System.Nullable<byte> oh
		{
			get
			{
				return this._oh;
			}
			set
			{
				if ((this._oh != value))
				{
					this.OnohChanging(value);
					this.SendPropertyChanging();
					this._oh = value;
					this.SendPropertyChanged("oh");
					this.OnohChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oi", DbType="TinyInt")]
		public System.Nullable<byte> oi
		{
			get
			{
				return this._oi;
			}
			set
			{
				if ((this._oi != value))
				{
					this.OnoiChanging(value);
					this.SendPropertyChanging();
					this._oi = value;
					this.SendPropertyChanged("oi");
					this.OnoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oj", DbType="TinyInt")]
		public System.Nullable<byte> oj
		{
			get
			{
				return this._oj;
			}
			set
			{
				if ((this._oj != value))
				{
					this.OnojChanging(value);
					this.SendPropertyChanging();
					this._oj = value;
					this.SendPropertyChanged("oj");
					this.OnojChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ok", DbType="TinyInt")]
		public System.Nullable<byte> ok
		{
			get
			{
				return this._ok;
			}
			set
			{
				if ((this._ok != value))
				{
					this.OnokChanging(value);
					this.SendPropertyChanging();
					this._ok = value;
					this.SendPropertyChanged("ok");
					this.OnokChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ol", DbType="TinyInt")]
		public System.Nullable<byte> ol
		{
			get
			{
				return this._ol;
			}
			set
			{
				if ((this._ol != value))
				{
					this.OnolChanging(value);
					this.SendPropertyChanging();
					this._ol = value;
					this.SendPropertyChanged("ol");
					this.OnolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aa", DbType="TinyInt")]
		public System.Nullable<byte> aa
		{
			get
			{
				return this._aa;
			}
			set
			{
				if ((this._aa != value))
				{
					this.OnaaChanging(value);
					this.SendPropertyChanging();
					this._aa = value;
					this.SendPropertyChanged("aa");
					this.OnaaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ab", DbType="TinyInt")]
		public System.Nullable<byte> ab
		{
			get
			{
				return this._ab;
			}
			set
			{
				if ((this._ab != value))
				{
					this.OnabChanging(value);
					this.SendPropertyChanging();
					this._ab = value;
					this.SendPropertyChanged("ab");
					this.OnabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ac", DbType="TinyInt")]
		public System.Nullable<byte> ac
		{
			get
			{
				return this._ac;
			}
			set
			{
				if ((this._ac != value))
				{
					this.OnacChanging(value);
					this.SendPropertyChanging();
					this._ac = value;
					this.SendPropertyChanged("ac");
					this.OnacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="TinyInt")]
		public System.Nullable<byte> ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this.OnadChanging(value);
					this.SendPropertyChanging();
					this._ad = value;
					this.SendPropertyChanged("ad");
					this.OnadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ae", DbType="TinyInt")]
		public System.Nullable<byte> ae
		{
			get
			{
				return this._ae;
			}
			set
			{
				if ((this._ae != value))
				{
					this.OnaeChanging(value);
					this.SendPropertyChanging();
					this._ae = value;
					this.SendPropertyChanged("ae");
					this.OnaeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_af", DbType="TinyInt")]
		public System.Nullable<byte> af
		{
			get
			{
				return this._af;
			}
			set
			{
				if ((this._af != value))
				{
					this.OnafChanging(value);
					this.SendPropertyChanging();
					this._af = value;
					this.SendPropertyChanged("af");
					this.OnafChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ag", DbType="TinyInt")]
		public System.Nullable<byte> ag
		{
			get
			{
				return this._ag;
			}
			set
			{
				if ((this._ag != value))
				{
					this.OnagChanging(value);
					this.SendPropertyChanging();
					this._ag = value;
					this.SendPropertyChanged("ag");
					this.OnagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ah", DbType="TinyInt")]
		public System.Nullable<byte> ah
		{
			get
			{
				return this._ah;
			}
			set
			{
				if ((this._ah != value))
				{
					this.OnahChanging(value);
					this.SendPropertyChanging();
					this._ah = value;
					this.SendPropertyChanged("ah");
					this.OnahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ai", DbType="TinyInt")]
		public System.Nullable<byte> ai
		{
			get
			{
				return this._ai;
			}
			set
			{
				if ((this._ai != value))
				{
					this.OnaiChanging(value);
					this.SendPropertyChanging();
					this._ai = value;
					this.SendPropertyChanged("ai");
					this.OnaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aj", DbType="TinyInt")]
		public System.Nullable<byte> aj
		{
			get
			{
				return this._aj;
			}
			set
			{
				if ((this._aj != value))
				{
					this.OnajChanging(value);
					this.SendPropertyChanging();
					this._aj = value;
					this.SendPropertyChanged("aj");
					this.OnajChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ak", DbType="TinyInt")]
		public System.Nullable<byte> ak
		{
			get
			{
				return this._ak;
			}
			set
			{
				if ((this._ak != value))
				{
					this.OnakChanging(value);
					this.SendPropertyChanging();
					this._ak = value;
					this.SendPropertyChanged("ak");
					this.OnakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_al", DbType="TinyInt")]
		public System.Nullable<byte> al
		{
			get
			{
				return this._al;
			}
			set
			{
				if ((this._al != value))
				{
					this.OnalChanging(value);
					this.SendPropertyChanging();
					this._al = value;
					this.SendPropertyChanged("al");
					this.OnalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ca", DbType="TinyInt")]
		public System.Nullable<byte> ca
		{
			get
			{
				return this._ca;
			}
			set
			{
				if ((this._ca != value))
				{
					this.OncaChanging(value);
					this.SendPropertyChanging();
					this._ca = value;
					this.SendPropertyChanged("ca");
					this.OncaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cb", DbType="TinyInt")]
		public System.Nullable<byte> cb
		{
			get
			{
				return this._cb;
			}
			set
			{
				if ((this._cb != value))
				{
					this.OncbChanging(value);
					this.SendPropertyChanging();
					this._cb = value;
					this.SendPropertyChanged("cb");
					this.OncbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cc", DbType="TinyInt")]
		public System.Nullable<byte> cc
		{
			get
			{
				return this._cc;
			}
			set
			{
				if ((this._cc != value))
				{
					this.OnccChanging(value);
					this.SendPropertyChanging();
					this._cc = value;
					this.SendPropertyChanged("cc");
					this.OnccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd", DbType="TinyInt")]
		public System.Nullable<byte> cd
		{
			get
			{
				return this._cd;
			}
			set
			{
				if ((this._cd != value))
				{
					this.OncdChanging(value);
					this.SendPropertyChanging();
					this._cd = value;
					this.SendPropertyChanged("cd");
					this.OncdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ce", DbType="TinyInt")]
		public System.Nullable<byte> ce
		{
			get
			{
				return this._ce;
			}
			set
			{
				if ((this._ce != value))
				{
					this.OnceChanging(value);
					this.SendPropertyChanging();
					this._ce = value;
					this.SendPropertyChanged("ce");
					this.OnceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cf", DbType="TinyInt")]
		public System.Nullable<byte> cf
		{
			get
			{
				return this._cf;
			}
			set
			{
				if ((this._cf != value))
				{
					this.OncfChanging(value);
					this.SendPropertyChanging();
					this._cf = value;
					this.SendPropertyChanged("cf");
					this.OncfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cg", DbType="TinyInt")]
		public System.Nullable<byte> cg
		{
			get
			{
				return this._cg;
			}
			set
			{
				if ((this._cg != value))
				{
					this.OncgChanging(value);
					this.SendPropertyChanging();
					this._cg = value;
					this.SendPropertyChanged("cg");
					this.OncgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ch", DbType="TinyInt")]
		public System.Nullable<byte> ch
		{
			get
			{
				return this._ch;
			}
			set
			{
				if ((this._ch != value))
				{
					this.OnchChanging(value);
					this.SendPropertyChanging();
					this._ch = value;
					this.SendPropertyChanged("ch");
					this.OnchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ci", DbType="TinyInt")]
		public System.Nullable<byte> ci
		{
			get
			{
				return this._ci;
			}
			set
			{
				if ((this._ci != value))
				{
					this.OnciChanging(value);
					this.SendPropertyChanging();
					this._ci = value;
					this.SendPropertyChanged("ci");
					this.OnciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cj", DbType="TinyInt")]
		public System.Nullable<byte> cj
		{
			get
			{
				return this._cj;
			}
			set
			{
				if ((this._cj != value))
				{
					this.OncjChanging(value);
					this.SendPropertyChanging();
					this._cj = value;
					this.SendPropertyChanged("cj");
					this.OncjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ck", DbType="TinyInt")]
		public System.Nullable<byte> ck
		{
			get
			{
				return this._ck;
			}
			set
			{
				if ((this._ck != value))
				{
					this.OnckChanging(value);
					this.SendPropertyChanging();
					this._ck = value;
					this.SendPropertyChanged("ck");
					this.OnckChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cl", DbType="TinyInt")]
		public System.Nullable<byte> cl
		{
			get
			{
				return this._cl;
			}
			set
			{
				if ((this._cl != value))
				{
					this.OnclChanging(value);
					this.SendPropertyChanging();
					this._cl = value;
					this.SendPropertyChanged("cl");
					this.OnclChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameF", DbType="NVarChar(50)")]
		public string NameF
		{
			get
			{
				return this._NameF;
			}
			set
			{
				if ((this._NameF != value))
				{
					this.OnNameFChanging(value);
					this.SendPropertyChanging();
					this._NameF = value;
					this.SendPropertyChanged("NameF");
					this.OnNameFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateNeo", DbType="NVarChar(10)")]
		public string DateNeo
		{
			get
			{
				return this._DateNeo;
			}
			set
			{
				if ((this._DateNeo != value))
				{
					this.OnDateNeoChanging(value);
					this.SendPropertyChanging();
					this._DateNeo = value;
					this.SendPropertyChanged("DateNeo");
					this.OnDateNeoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Meli", DbType="NVarChar(10)")]
		public string Meli
		{
			get
			{
				return this._Meli;
			}
			set
			{
				if ((this._Meli != value))
				{
					this.OnMeliChanging(value);
					this.SendPropertyChanging();
					this._Meli = value;
					this.SendPropertyChanged("Meli");
					this.OnMeliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adress", DbType="NVarChar(100)")]
		public string Adress
		{
			get
			{
				return this._Adress;
			}
			set
			{
				if ((this._Adress != value))
				{
					this.OnAdressChanging(value);
					this.SendPropertyChanging();
					this._Adress = value;
					this.SendPropertyChanged("Adress");
					this.OnAdressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneH", DbType="NVarChar(15)")]
		public string PhoneH
		{
			get
			{
				return this._PhoneH;
			}
			set
			{
				if ((this._PhoneH != value))
				{
					this.OnPhoneHChanging(value);
					this.SendPropertyChanging();
					this._PhoneH = value;
					this.SendPropertyChanged("PhoneH");
					this.OnPhoneHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneM", DbType="NVarChar(15)")]
		public string PhoneM
		{
			get
			{
				return this._PhoneM;
			}
			set
			{
				if ((this._PhoneM != value))
				{
					this.OnPhoneMChanging(value);
					this.SendPropertyChanging();
					this._PhoneM = value;
					this.SendPropertyChanged("PhoneM");
					this.OnPhoneMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberSh", DbType="NVarChar(10)")]
		public string NumberSh
		{
			get
			{
				return this._NumberSh;
			}
			set
			{
				if ((this._NumberSh != value))
				{
					this.OnNumberShChanging(value);
					this.SendPropertyChanging();
					this._NumberSh = value;
					this.SendPropertyChanged("NumberSh");
					this.OnNumberShChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoEsh", DbType="NVarChar(100)")]
		public string LoEsh
		{
			get
			{
				return this._LoEsh;
			}
			set
			{
				if ((this._LoEsh != value))
				{
					this.OnLoEshChanging(value);
					this.SendPropertyChanging();
					this._LoEsh = value;
					this.SendPropertyChanged("LoEsh");
					this.OnLoEshChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N", DbType="Int")]
		public System.Nullable<int> N
		{
			get
			{
				return this._N;
			}
			set
			{
				if ((this._N != value))
				{
					this.OnNChanging(value);
					this.SendPropertyChanging();
					this._N = value;
					this.SendPropertyChanged("N");
					this.OnNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E", DbType="Int")]
		public System.Nullable<int> E
		{
			get
			{
				return this._E;
			}
			set
			{
				if ((this._E != value))
				{
					this.OnEChanging(value);
					this.SendPropertyChanging();
					this._E = value;
					this.SendPropertyChanged("E");
					this.OnEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_O", DbType="Int")]
		public System.Nullable<int> O
		{
			get
			{
				return this._O;
			}
			set
			{
				if ((this._O != value))
				{
					this.OnOChanging(value);
					this.SendPropertyChanging();
					this._O = value;
					this.SendPropertyChanged("O");
					this.OnOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="Int")]
		public System.Nullable<int> A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this.OnAChanging(value);
					this.SendPropertyChanging();
					this._A = value;
					this.SendPropertyChanged("A");
					this.OnAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C", DbType="Int")]
		public System.Nullable<int> C
		{
			get
			{
				return this._C;
			}
			set
			{
				if ((this._C != value))
				{
					this.OnCChanging(value);
					this.SendPropertyChanging();
					this._C = value;
					this.SendPropertyChanged("C");
					this.OnCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paj", DbType="TinyInt")]
		public System.Nullable<byte> paj
		{
			get
			{
				return this._paj;
			}
			set
			{
				if ((this._paj != value))
				{
					this.OnpajChanging(value);
					this.SendPropertyChanging();
					this._paj = value;
					this.SendPropertyChanged("paj");
					this.OnpajChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pad", DbType="TinyInt")]
		public System.Nullable<byte> pad
		{
			get
			{
				return this._pad;
			}
			set
			{
				if ((this._pad != value))
				{
					this.OnpadChanging(value);
					this.SendPropertyChanging();
					this._pad = value;
					this.SendPropertyChanged("pad");
					this.OnpadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pba", DbType="TinyInt")]
		public System.Nullable<byte> pba
		{
			get
			{
				return this._pba;
			}
			set
			{
				if ((this._pba != value))
				{
					this.OnpbaChanging(value);
					this.SendPropertyChanging();
					this._pba = value;
					this.SendPropertyChanged("pba");
					this.OnpbaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pbh", DbType="TinyInt")]
		public System.Nullable<byte> pbh
		{
			get
			{
				return this._pbh;
			}
			set
			{
				if ((this._pbh != value))
				{
					this.OnpbhChanging(value);
					this.SendPropertyChanging();
					this._pbh = value;
					this.SendPropertyChanged("pbh");
					this.OnpbhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pcd", DbType="TinyInt")]
		public System.Nullable<byte> pcd
		{
			get
			{
				return this._pcd;
			}
			set
			{
				if ((this._pcd != value))
				{
					this.OnpcdChanging(value);
					this.SendPropertyChanging();
					this._pcd = value;
					this.SendPropertyChanged("pcd");
					this.OnpcdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pch", DbType="TinyInt")]
		public System.Nullable<byte> pch
		{
			get
			{
				return this._pch;
			}
			set
			{
				if ((this._pch != value))
				{
					this.OnpchChanging(value);
					this.SendPropertyChanging();
					this._pch = value;
					this.SendPropertyChanged("pch");
					this.OnpchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pdb", DbType="TinyInt")]
		public System.Nullable<byte> pdb
		{
			get
			{
				return this._pdb;
			}
			set
			{
				if ((this._pdb != value))
				{
					this.OnpdbChanging(value);
					this.SendPropertyChanging();
					this._pdb = value;
					this.SendPropertyChanged("pdb");
					this.OnpdbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pdj", DbType="TinyInt")]
		public System.Nullable<byte> pdj
		{
			get
			{
				return this._pdj;
			}
			set
			{
				if ((this._pdj != value))
				{
					this.OnpdjChanging(value);
					this.SendPropertyChanging();
					this._pdj = value;
					this.SendPropertyChanged("pdj");
					this.OnpdjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pej", DbType="TinyInt")]
		public System.Nullable<byte> pej
		{
			get
			{
				return this._pej;
			}
			set
			{
				if ((this._pej != value))
				{
					this.OnpejChanging(value);
					this.SendPropertyChanging();
					this._pej = value;
					this.SendPropertyChanged("pej");
					this.OnpejChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peh", DbType="TinyInt")]
		public System.Nullable<byte> peh
		{
			get
			{
				return this._peh;
			}
			set
			{
				if ((this._peh != value))
				{
					this.OnpehChanging(value);
					this.SendPropertyChanging();
					this._peh = value;
					this.SendPropertyChanged("peh");
					this.OnpehChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pfa", DbType="TinyInt")]
		public System.Nullable<byte> pfa
		{
			get
			{
				return this._pfa;
			}
			set
			{
				if ((this._pfa != value))
				{
					this.OnpfaChanging(value);
					this.SendPropertyChanging();
					this._pfa = value;
					this.SendPropertyChanged("pfa");
					this.OnpfaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pfb", DbType="TinyInt")]
		public System.Nullable<byte> pfb
		{
			get
			{
				return this._pfb;
			}
			set
			{
				if ((this._pfb != value))
				{
					this.OnpfbChanging(value);
					this.SendPropertyChanging();
					this._pfb = value;
					this.SendPropertyChanged("pfb");
					this.OnpfbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pgj", DbType="TinyInt")]
		public System.Nullable<byte> pgj
		{
			get
			{
				return this._pgj;
			}
			set
			{
				if ((this._pgj != value))
				{
					this.OnpgjChanging(value);
					this.SendPropertyChanging();
					this._pgj = value;
					this.SendPropertyChanged("pgj");
					this.OnpgjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pgh", DbType="TinyInt")]
		public System.Nullable<byte> pgh
		{
			get
			{
				return this._pgh;
			}
			set
			{
				if ((this._pgh != value))
				{
					this.OnpghChanging(value);
					this.SendPropertyChanging();
					this._pgh = value;
					this.SendPropertyChanged("pgh");
					this.OnpghChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pha", DbType="TinyInt")]
		public System.Nullable<byte> pha
		{
			get
			{
				return this._pha;
			}
			set
			{
				if ((this._pha != value))
				{
					this.OnphaChanging(value);
					this.SendPropertyChanging();
					this._pha = value;
					this.SendPropertyChanged("pha");
					this.OnphaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phb", DbType="TinyInt")]
		public System.Nullable<byte> phb
		{
			get
			{
				return this._phb;
			}
			set
			{
				if ((this._phb != value))
				{
					this.OnphbChanging(value);
					this.SendPropertyChanging();
					this._phb = value;
					this.SendPropertyChanged("phb");
					this.OnphbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pia", DbType="TinyInt")]
		public System.Nullable<byte> pia
		{
			get
			{
				return this._pia;
			}
			set
			{
				if ((this._pia != value))
				{
					this.OnpiaChanging(value);
					this.SendPropertyChanging();
					this._pia = value;
					this.SendPropertyChanged("pia");
					this.OnpiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pih", DbType="TinyInt")]
		public System.Nullable<byte> pih
		{
			get
			{
				return this._pih;
			}
			set
			{
				if ((this._pih != value))
				{
					this.OnpihChanging(value);
					this.SendPropertyChanging();
					this._pih = value;
					this.SendPropertyChanged("pih");
					this.OnpihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pjb", DbType="TinyInt")]
		public System.Nullable<byte> pjb
		{
			get
			{
				return this._pjb;
			}
			set
			{
				if ((this._pjb != value))
				{
					this.OnpjbChanging(value);
					this.SendPropertyChanging();
					this._pjb = value;
					this.SendPropertyChanged("pjb");
					this.OnpjbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pjh", DbType="TinyInt")]
		public System.Nullable<byte> pjh
		{
			get
			{
				return this._pjh;
			}
			set
			{
				if ((this._pjh != value))
				{
					this.OnpjhChanging(value);
					this.SendPropertyChanging();
					this._pjh = value;
					this.SendPropertyChanged("pjh");
					this.OnpjhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pka", DbType="TinyInt")]
		public System.Nullable<byte> pka
		{
			get
			{
				return this._pka;
			}
			set
			{
				if ((this._pka != value))
				{
					this.OnpkaChanging(value);
					this.SendPropertyChanging();
					this._pka = value;
					this.SendPropertyChanged("pka");
					this.OnpkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pkd", DbType="TinyInt")]
		public System.Nullable<byte> pkd
		{
			get
			{
				return this._pkd;
			}
			set
			{
				if ((this._pkd != value))
				{
					this.OnpkdChanging(value);
					this.SendPropertyChanging();
					this._pkd = value;
					this.SendPropertyChanged("pkd");
					this.OnpkdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pld", DbType="TinyInt")]
		public System.Nullable<byte> pld
		{
			get
			{
				return this._pld;
			}
			set
			{
				if ((this._pld != value))
				{
					this.OnpldChanging(value);
					this.SendPropertyChanging();
					this._pld = value;
					this.SendPropertyChanged("pld");
					this.OnpldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plh", DbType="TinyInt")]
		public System.Nullable<byte> plh
		{
			get
			{
				return this._plh;
			}
			set
			{
				if ((this._plh != value))
				{
					this.OnplhChanging(value);
					this.SendPropertyChanging();
					this._plh = value;
					this.SendPropertyChanged("plh");
					this.OnplhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pmb", DbType="TinyInt")]
		public System.Nullable<byte> pmb
		{
			get
			{
				return this._pmb;
			}
			set
			{
				if ((this._pmb != value))
				{
					this.OnpmbChanging(value);
					this.SendPropertyChanging();
					this._pmb = value;
					this.SendPropertyChanged("pmb");
					this.OnpmbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pmh", DbType="TinyInt")]
		public System.Nullable<byte> pmh
		{
			get
			{
				return this._pmh;
			}
			set
			{
				if ((this._pmh != value))
				{
					this.OnpmhChanging(value);
					this.SendPropertyChanging();
					this._pmh = value;
					this.SendPropertyChanged("pmh");
					this.OnpmhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pnj", DbType="TinyInt")]
		public System.Nullable<byte> pnj
		{
			get
			{
				return this._pnj;
			}
			set
			{
				if ((this._pnj != value))
				{
					this.OnpnjChanging(value);
					this.SendPropertyChanging();
					this._pnj = value;
					this.SendPropertyChanged("pnj");
					this.OnpnjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pnd", DbType="TinyInt")]
		public System.Nullable<byte> pnd
		{
			get
			{
				return this._pnd;
			}
			set
			{
				if ((this._pnd != value))
				{
					this.OnpndChanging(value);
					this.SendPropertyChanging();
					this._pnd = value;
					this.SendPropertyChanged("pnd");
					this.OnpndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ppb", DbType="TinyInt")]
		public System.Nullable<byte> ppb
		{
			get
			{
				return this._ppb;
			}
			set
			{
				if ((this._ppb != value))
				{
					this.OnppbChanging(value);
					this.SendPropertyChanging();
					this._ppb = value;
					this.SendPropertyChanged("ppb");
					this.OnppbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ppd", DbType="TinyInt")]
		public System.Nullable<byte> ppd
		{
			get
			{
				return this._ppd;
			}
			set
			{
				if ((this._ppd != value))
				{
					this.OnppdChanging(value);
					this.SendPropertyChanging();
					this._ppd = value;
					this.SendPropertyChanged("ppd");
					this.OnppdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_poa", DbType="TinyInt")]
		public System.Nullable<byte> poa
		{
			get
			{
				return this._poa;
			}
			set
			{
				if ((this._poa != value))
				{
					this.OnpoaChanging(value);
					this.SendPropertyChanging();
					this._poa = value;
					this.SendPropertyChanged("poa");
					this.OnpoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pod", DbType="TinyInt")]
		public System.Nullable<byte> pod
		{
			get
			{
				return this._pod;
			}
			set
			{
				if ((this._pod != value))
				{
					this.OnpodChanging(value);
					this.SendPropertyChanging();
					this._pod = value;
					this.SendPropertyChanged("pod");
					this.OnpodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pqb", DbType="TinyInt")]
		public System.Nullable<byte> pqb
		{
			get
			{
				return this._pqb;
			}
			set
			{
				if ((this._pqb != value))
				{
					this.OnpqbChanging(value);
					this.SendPropertyChanging();
					this._pqb = value;
					this.SendPropertyChanged("pqb");
					this.OnpqbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pqj", DbType="TinyInt")]
		public System.Nullable<byte> pqj
		{
			get
			{
				return this._pqj;
			}
			set
			{
				if ((this._pqj != value))
				{
					this.OnpqjChanging(value);
					this.SendPropertyChanging();
					this._pqj = value;
					this.SendPropertyChanged("pqj");
					this.OnpqjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pua", DbType="TinyInt")]
		public System.Nullable<byte> pua
		{
			get
			{
				return this._pua;
			}
			set
			{
				if ((this._pua != value))
				{
					this.OnpuaChanging(value);
					this.SendPropertyChanging();
					this._pua = value;
					this.SendPropertyChanged("pua");
					this.OnpuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puj", DbType="TinyInt")]
		public System.Nullable<byte> puj
		{
			get
			{
				return this._puj;
			}
			set
			{
				if ((this._puj != value))
				{
					this.OnpujChanging(value);
					this.SendPropertyChanging();
					this._puj = value;
					this.SendPropertyChanged("puj");
					this.OnpujChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwa", DbType="TinyInt")]
		public System.Nullable<byte> pwa
		{
			get
			{
				return this._pwa;
			}
			set
			{
				if ((this._pwa != value))
				{
					this.OnpwaChanging(value);
					this.SendPropertyChanging();
					this._pwa = value;
					this.SendPropertyChanged("pwa");
					this.OnpwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwj", DbType="TinyInt")]
		public System.Nullable<byte> pwj
		{
			get
			{
				return this._pwj;
			}
			set
			{
				if ((this._pwj != value))
				{
					this.OnpwjChanging(value);
					this.SendPropertyChanging();
					this._pwj = value;
					this.SendPropertyChanged("pwj");
					this.OnpwjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pxb", DbType="TinyInt")]
		public System.Nullable<byte> pxb
		{
			get
			{
				return this._pxb;
			}
			set
			{
				if ((this._pxb != value))
				{
					this.OnpxbChanging(value);
					this.SendPropertyChanging();
					this._pxb = value;
					this.SendPropertyChanged("pxb");
					this.OnpxbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pxd", DbType="TinyInt")]
		public System.Nullable<byte> pxd
		{
			get
			{
				return this._pxd;
			}
			set
			{
				if ((this._pxd != value))
				{
					this.OnpxdChanging(value);
					this.SendPropertyChanging();
					this._pxd = value;
					this.SendPropertyChanged("pxd");
					this.OnpxdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PA", DbType="Int")]
		public System.Nullable<int> PA
		{
			get
			{
				return this._PA;
			}
			set
			{
				if ((this._PA != value))
				{
					this.OnPAChanging(value);
					this.SendPropertyChanging();
					this._PA = value;
					this.SendPropertyChanged("PA");
					this.OnPAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PB", DbType="Int")]
		public System.Nullable<int> PB
		{
			get
			{
				return this._PB;
			}
			set
			{
				if ((this._PB != value))
				{
					this.OnPBChanging(value);
					this.SendPropertyChanging();
					this._PB = value;
					this.SendPropertyChanged("PB");
					this.OnPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PJ", DbType="Int")]
		public System.Nullable<int> PJ
		{
			get
			{
				return this._PJ;
			}
			set
			{
				if ((this._PJ != value))
				{
					this.OnPJChanging(value);
					this.SendPropertyChanging();
					this._PJ = value;
					this.SendPropertyChanged("PJ");
					this.OnPJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PD", DbType="Int")]
		public System.Nullable<int> PD
		{
			get
			{
				return this._PD;
			}
			set
			{
				if ((this._PD != value))
				{
					this.OnPDChanging(value);
					this.SendPropertyChanging();
					this._PD = value;
					this.SendPropertyChanged("PD");
					this.OnPDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PH", DbType="Int")]
		public System.Nullable<int> PH
		{
			get
			{
				return this._PH;
			}
			set
			{
				if ((this._PH != value))
				{
					this.OnPHChanging(value);
					this.SendPropertyChanging();
					this._PH = value;
					this.SendPropertyChanged("PH");
					this.OnPHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="Int")]
		public System.Nullable<int> Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this.OnNumberChanging(value);
					this.SendPropertyChanging();
					this._Number = value;
					this.SendPropertyChanged("Number");
					this.OnNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Peyvast", DbType="NVarChar(50)")]
		public string Peyvast
		{
			get
			{
				return this._Peyvast;
			}
			set
			{
				if ((this._Peyvast != value))
				{
					this.OnPeyvastChanging(value);
					this.SendPropertyChanging();
					this._Peyvast = value;
					this.SendPropertyChanged("Peyvast");
					this.OnPeyvastChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResultNeo", DbType="NVarChar(500)")]
		public string ResultNeo
		{
			get
			{
				return this._ResultNeo;
			}
			set
			{
				if ((this._ResultNeo != value))
				{
					this.OnResultNeoChanging(value);
					this.SendPropertyChanging();
					this._ResultNeo = value;
					this.SendPropertyChanged("ResultNeo");
					this.OnResultNeoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShoghlNext", DbType="NVarChar(100)")]
		public string ShoghlNext
		{
			get
			{
				return this._ShoghlNext;
			}
			set
			{
				if ((this._ShoghlNext != value))
				{
					this.OnShoghlNextChanging(value);
					this.SendPropertyChanging();
					this._ShoghlNext = value;
					this.SendPropertyChanged("ShoghlNext");
					this.OnShoghlNextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(250)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int")]
		public System.Nullable<int> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
